leftnav:
- identifier: 46b0625e-677d-8564-39fd-035e85f1646a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 759f5a5a-daf1-51eb-bd31-9bb50b63b725
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 6bf82f16-1acd-a107-5811-ce49254c6ea6
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 549db3c7-330e-b0d5-d5b3-218a8dca6dff
  name: Assignments
  url: /pages/assignments
  weight: 40
